# Generated by Django 2.2.7 on 2019-11-30 05:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='name_text',
            new_name='name',
        ),
        migrations.AddField(
            model_name='meal',
            name='grade',
            field=models.IntegerField(null=True),
        ),
    ]
