# Generated by Django 2.2.7 on 2019-12-28 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20191228_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='grade',
        ),
    ]
