# Generated by Django 2.2.7 on 2020-01-20 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_auto_20200111_2312'),
    ]

    operations = [
        migrations.AddField(
            model_name='label',
            name='color_blue',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='label',
            name='color_green',
            field=models.IntegerField(default=100),
        ),
        migrations.AddField(
            model_name='label',
            name='color_red',
            field=models.IntegerField(default=100),
        ),
    ]
