# Generated by Django 2.2.7 on 2020-01-21 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_auto_20200120_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='color_blue',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='color_green',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='label',
            name='color_red',
            field=models.IntegerField(),
        ),
    ]
