# Generated by Django 3.0.2 on 2020-02-16 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_auto_20200121_2211'),
    ]

    operations = [
        migrations.AlterField(
            model_name='label',
            name='text',
            field=models.CharField(max_length=12),
        ),
    ]
