# Generated by Django 3.0.2 on 2020-03-28 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_auto_20200223_0711'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Meal',
            new_name='Dinner',
        ),
    ]
