# Generated by Django 3.0.2 on 2020-04-01 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0016_create_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='dinner',
            field=models.ForeignKey(to='main.dinner', on_delete=models.CASCADE, null=True)
        ),
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.ForeignKey(to='main.date', on_delete=models.CASCADE)
        )
    ]
