# Generated by Django 3.0.2 on 2020-04-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0017_auto_20200401_2105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date',
        ),
        migrations.AddField(
            model_name='plan',
            name='date',
            field=models.DateField()
        ),
    ]
