# Generated by Django 3.0.2 on 2020-04-11 18:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0018_change_datefield'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='date',
        ),
        migrations.AddField(
            model_name='plan',
            name='name',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
    ]
