# Generated by Django 3.0.2 on 2020-04-24 21:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0024_auto_20200424_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weeklyplan',
            name='friday',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='monday',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='saturday',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='sunday',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='thursday',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='tuesday',
        ),
        migrations.RemoveField(
            model_name='weeklyplan',
            name='wednesday',
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='friday_dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friday', to='main.Dinner'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='friday_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='monday_dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monday', to='main.Dinner'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='monday_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='saturday_dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='saturday', to='main.Dinner'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='saturday_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='sunday_dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sunday', to='main.Dinner'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='sunday_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='thursday_dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thursday', to='main.Dinner'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='thursday_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='tuesday_dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tuesday', to='main.Dinner'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='tuesday_text',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='wednesday_dinner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wednesday', to='main.Dinner'),
        ),
        migrations.AddField(
            model_name='weeklyplan',
            name='wednesday_text',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
