# Generated by Django 3.0.2 on 2020-04-25 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0025_auto_20200424_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weeklyplan',
            name='friday_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='monday_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='saturday_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='sunday_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='thursday_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='tuesday_text',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='weeklyplan',
            name='wednesday_text',
            field=models.CharField(default='', max_length=100),
        ),
    ]
