# Generated by Django 3.0.2 on 2020-06-05 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0026_auto_20200425_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='info',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
